services:
  - docker
script:
  - docker image build -t 2048docker01/travis_test .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push 2048docker01/travis_test
